In [1]:
print("SHANU KUMAR")
print(187159)
print("SEC- A")

print("Q6. Design and implement a Deep CNN to solve hand written character recognition problem for A to Z and 0 to 9 letters and digits respectively.")

SHANU KUMAR
187159
SEC- A
Q6. Design and implement a Deep CNN to solve hand written character recognition problem for A to Z and 0 to 9 letters and digits respectively.


In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.datasets import fetch_openml
from sklearn.model_selection import train_test_split
import json
from keras.utils.np_utils import to_categorical
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import Flatten
from keras.layers.convolutional import Conv2D
from keras.layers.convolutional import MaxPooling2D
from keras.utils import np_utils

Loading the MNIST Dataset

In [2]:
features, labels = fetch_openml('mnist_784', version=1, return_X_y=True)

In [3]:
features = (features/255).astype('float32')

Reshaping the 784 pixels into 28 x 28 x 1

In [4]:
features = features.reshape(features.shape[0],28,28,1).astype('float32')


Converting the labels to 1-hot encoded format so as to allow for simple subtraction in delta calculation step at the outputs of the network.

In [5]:
labels = to_categorical(labels)

Splitting into training and testing parts

In [6]:
X_train, X_test, Y_train, Y_test = train_test_split(features, labels, test_size=0.15, random_state=37)

**Convolutional Neural Network Model**

The Kernel

Size of Input Layer = 28 x 28

Activation Function at Output layer: The softmax activation function computes the following -

$softmax(z) = \frac{exp(z)}{\sum_{j}^{ }exp(z_j)}$

This softmax gives us the probability of each prediction label.

In [7]:
def defineModel(numClasses):
    model = Sequential()
    model.add(Conv2D(32, (5, 5), input_shape=(28, 28, 1), activation='relu'))
    model.add(MaxPooling2D(pool_size=(2, 2)))
    model.add(Dropout(0.2))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(numClasses, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model


Splitting the test dataset into validation and test parts

In [8]:
X_test, X_val, Y_test, Y_val = train_test_split(X_test, Y_test, test_size=0.1)

Fitting the model

In [9]:
model = defineModel(Y_test.shape[1])
history = model.fit(X_train, Y_train, validation_data=(X_val, Y_val), epochs=10, batch_size=200, verbose=2)

Epoch 1/10
298/298 - 27s - loss: 0.2612 - accuracy: 0.9240 - val_loss: 0.0865 - val_accuracy: 0.9752 - 27s/epoch - 89ms/step
Epoch 2/10
298/298 - 25s - loss: 0.0811 - accuracy: 0.9761 - val_loss: 0.0612 - val_accuracy: 0.9771 - 25s/epoch - 85ms/step
Epoch 3/10
298/298 - 25s - loss: 0.0556 - accuracy: 0.9826 - val_loss: 0.0459 - val_accuracy: 0.9829 - 25s/epoch - 85ms/step
Epoch 4/10
298/298 - 25s - loss: 0.0428 - accuracy: 0.9865 - val_loss: 0.0422 - val_accuracy: 0.9857 - 25s/epoch - 84ms/step
Epoch 5/10
298/298 - 25s - loss: 0.0354 - accuracy: 0.9890 - val_loss: 0.0414 - val_accuracy: 0.9848 - 25s/epoch - 84ms/step
Epoch 6/10
298/298 - 25s - loss: 0.0284 - accuracy: 0.9910 - val_loss: 0.0298 - val_accuracy: 0.9914 - 25s/epoch - 84ms/step
Epoch 7/10
298/298 - 25s - loss: 0.0256 - accuracy: 0.9913 - val_loss: 0.0372 - val_accuracy: 0.9857 - 25s/epoch - 84ms/step
Epoch 8/10
298/298 - 25s - loss: 0.0212 - accuracy: 0.9930 - val_loss: 0.0265 - val_accuracy: 0.9933 - 25s/epoch - 84ms/step


In [10]:
print("Model performance on test data")
results = model.evaluate(X_test, Y_test, batch_size=200)
print("Test loss, Test Accuracy : ", results)

Model performance on test data
48/48 [==============================] - 1s 23ms/step - loss: 0.0356 - accuracy: 0.9906
Test loss, Test Accuracy :  [0.03564070537686348, 0.9905819892883301]



Layer dimensions and weights

In [11]:
for layer in model.layers:
  print("Input shape: ",layer.input_shape)
  print("Output shape: ",layer.output_shape)
  print("Weights: ",layer.weights)

Input shape:  (None, 28, 28, 1)
Output shape:  (None, 24, 24, 32)
Weights:  [<tf.Variable 'conv2d/kernel:0' shape=(5, 5, 1, 32) dtype=float32, numpy=
array([[[[-1.95780769e-02, -2.69543320e-01, -1.25398844e-01,
           2.49939058e-02,  9.97524709e-02, -1.75682783e-01,
          -1.55136012e-03, -3.19653958e-01,  1.23836115e-01,
           7.17853457e-02, -4.67495471e-02, -2.25886971e-01,
          -9.66317579e-02,  6.72414387e-03, -9.81545299e-02,
           1.29290730e-01,  1.05141744e-01,  5.60422912e-02,
          -4.66229171e-01, -1.71699166e-01, -1.89684898e-01,
          -3.09076160e-02,  1.92915536e-02, -1.47407185e-02,
          -9.75706950e-02,  5.44439144e-02, -3.61431427e-02,
          -1.89888664e-02,  9.51208770e-02,  2.14892812e-02,
          -9.24689844e-02, -1.36358170e-02]],

        [[-2.05274418e-01, -6.20691366e-02, -5.62170409e-02,
           1.12512834e-01,  9.80797186e-02, -1.97223783e-01,
          -1.71532556e-01, -2.49205902e-01,  2.59463005e-02,
          

# **Loading Handwritten Character Dataset**

In [12]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [13]:
# importing required modules
from zipfile import ZipFile
  
# specifying the zip file name
file_name = "/content/gdrive/MyDrive/Handwritten.zip"
  
# opening the zip file in READ mode
def zipping(file_name):
  with ZipFile(file_name, 'r') as zip1:

    # printing all the contents of the zip file
    zip1.printdir()
  
    # extracting all the files
    print('Extracting all the files now...')
    zip1.extractall()
    print('Done!')
zipping(file_name)

File Name                                             Modified             Size
A_Z Handwritten Data.csv                       2019-09-26 08:18:04    698907044
A_Z Handwritten Data/A_Z Handwritten Data.csv  2019-09-26 08:18:56    698907044
Extracting all the files now...
Done!


In [14]:

df = pd.read_csv('A_Z Handwritten Data.csv')
print(df.shape)

(372450, 785)


Taking subset of the dataset (first 60000 rows)

In [15]:
df = np.array(df)
X = df[:60000,1:785]
Y = df[:60000,0:1]

In [16]:
print(X.shape)
print(Y.shape)
print(np.unique(Y))

(60000, 784)
(60000, 1)
[0 1 2 3 4]



Normalizing feature set entries and converting labels to 1-hot encoded form (same as above done for MNIST dataset)

In [17]:
X = (X/255).astype('float32')
Y = to_categorical(Y)

In [18]:
X = X.reshape(X.shape[0],28,28,1).astype('float32')

In [19]:
CX_train, CX_test, CY_train, CY_test = train_test_split(X, Y, test_size=0.15, random_state=37)

In [20]:
CX_test, CX_val, CY_test, CY_val = train_test_split(CX_test, CY_test, test_size=0.1)

Fitting the model

In [21]:
model = defineModel(CY_test.shape[1])
history = model.fit(CX_train, CY_train, validation_data=(CX_val, CY_val), epochs=10, batch_size=200, verbose=2)


Epoch 1/10
255/255 - 28s - loss: 0.1343 - accuracy: 0.9568 - val_loss: 0.0442 - val_accuracy: 0.9911 - 28s/epoch - 110ms/step
Epoch 2/10
255/255 - 27s - loss: 0.0377 - accuracy: 0.9889 - val_loss: 0.0318 - val_accuracy: 0.9911 - 27s/epoch - 105ms/step
Epoch 3/10
255/255 - 22s - loss: 0.0234 - accuracy: 0.9929 - val_loss: 0.0332 - val_accuracy: 0.9922 - 22s/epoch - 88ms/step
Epoch 4/10
255/255 - 22s - loss: 0.0187 - accuracy: 0.9946 - val_loss: 0.0245 - val_accuracy: 0.9956 - 22s/epoch - 87ms/step
Epoch 5/10
255/255 - 22s - loss: 0.0136 - accuracy: 0.9958 - val_loss: 0.0281 - val_accuracy: 0.9922 - 22s/epoch - 87ms/step
Epoch 6/10
255/255 - 22s - loss: 0.0096 - accuracy: 0.9975 - val_loss: 0.0229 - val_accuracy: 0.9944 - 22s/epoch - 87ms/step
Epoch 7/10
255/255 - 22s - loss: 0.0084 - accuracy: 0.9974 - val_loss: 0.0188 - val_accuracy: 0.9922 - 22s/epoch - 87ms/step
Epoch 8/10
255/255 - 22s - loss: 0.0063 - accuracy: 0.9981 - val_loss: 0.0123 - val_accuracy: 0.9967 - 22s/epoch - 87ms/ste

In [22]:
print("Model performance on test data")
results = model.evaluate(CX_test, CY_test, batch_size=200)
print("Test loss, Test Accuracy : ", results)

Model performance on test data
41/41 [==============================] - 1s 22ms/step - loss: 0.0087 - accuracy: 0.9968
Test loss, Test Accuracy :  [0.008712529204785824, 0.9967901110649109]


In [23]:
for layer in model.layers:
  print("Input shape: ",layer.input_shape)
  print("Output shape: ",layer.output_shape)
  print("Weights: ",layer.weights)

Input shape:  (None, 28, 28, 1)
Output shape:  (None, 24, 24, 32)
Weights:  [<tf.Variable 'conv2d_1/kernel:0' shape=(5, 5, 1, 32) dtype=float32, numpy=
array([[[[-1.13694943e-01,  6.22865744e-03,  3.88097540e-02,
           1.06864676e-01, -6.44118935e-02,  9.76069346e-02,
          -1.20216433e-03,  1.47789881e-01, -8.87349546e-02,
          -9.19312146e-03, -2.84478243e-04, -7.47711286e-02,
           4.09216061e-03, -5.83960861e-02,  1.18788160e-01,
           1.03381738e-01,  8.80601779e-02, -4.48010862e-02,
           8.25568940e-03, -6.89679608e-02,  3.55210602e-02,
           1.49563625e-01,  4.56276722e-02,  5.49766310e-02,
          -2.44717263e-02,  1.03228137e-01, -2.32782662e-02,
          -3.70412618e-02,  7.85606075e-03,  1.04466602e-01,
          -1.63080636e-02,  4.07871753e-02]],

        [[-8.66146088e-02, -5.38305789e-02,  2.39552241e-02,
          -1.19831003e-02, -1.47601843e-01,  5.81342168e-02,
          -1.16165802e-01,  3.67017128e-02, -9.58423689e-02,
        