#        *Machine Learning Assignment 7*

---
Name: SHANU KUMAR\
Roll No.: 187159\
Class : CSE 4A

---

Q7. Implement a genetic algorithm program to successfully classify examples in the 2 input EXOR problem using Gabil’s method
Using genetic algorithm we are trying to optimize the weights given the target function. The aim is to converge the weights such that classification is optimal.



In [1]:
## IMPORTING REQUIRED LIBRARIES
import numpy as np
import random

In [2]:
## TRUTH TABLE FOR 2 BOOLEAN VARIABLES
X = [1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1]
X = np.reshape(X, (4, 3))

## -1 INDICATES 0 AND 1 INDICATES 1
y = [-1, 1, 1, -1]
y = np.reshape(y, (4, 1))

In [3]:
## CREATING INITIAL POPULATION
no_output = 4
num_weights = 3
population_size = (no_output, num_weights)

new_population = np.random.uniform(low = -5, high = 5, size = population_size)

In [4]:
## FITNESS FUNCTION
def Fitness(X, y, population):
    fitness = np.zeros(len(population))
    for i in range(len(population)):
        print("Member of population : {}".format(i))
        e = 0
        for j in range(len(X)):
            val = np.square(np.dot(X[j], population[i].T) - y[j])
            e = e + val
            for k in range(X.shape[1]):
                if k != 3:
                    print("({})({}) + ".format(X[j, k], population[i, k]), end = '')
                else:
                    print("({})({}) = {} ".format(X[j, k], population[i, k], val))
        avg = e/len(X)
        print("Dataset average = ({})/({}) = {}\n".format(e, len(X), avg))
        fitness[i] = avg
    
    return fitness

In [5]:
## SELECTING BEST INDIVIDUALS OF CURRENT GENERATION TO BECOME PARENTS OF NEXT GENERATION
def SelectMatingPool(population, fitness, num_parents):
    parents = np.empty((num_parents, population.shape[1]))
    parent_idx = []
    for p in range(num_parents):
        pos = np.argmin(fitness)
        parent_idx.append(pos)
        parents[p, :] = population[pos, :]
        fitness[pos] = np.inf
    
    print("Parents : \n{}".format(parents))
    return parents

In [6]:
## CROSSING OVER GENES INDICATES NEW GENERATION IS BEING FORMED
def Crossover(parents, offspring_size):
    os = np.empty(offspring_size)
    cp = np.uint8(offspring_size[1]/2)

    for k in range(offspring_size[0]):
        print("Offspring number : {}".format(k))
        p1 = k%parents.shape[0]
        p2 = (k+1)%parents.shape[0]
        print("{} -> ".format(os[k]), end='')
        os[k, 0:cp] = parents[p1, 0:cp] ## first half from p1 and second half from p2
        os[k, cp:] = parents[p2, cp:] ## opposite of above
        print("{}".format(os[k]))
        
    
    return os

In [7]:
## SOME OF THE NEW MEMBERS OF THE POPULATION ARE MUTATED RANDOMLY
def Mutation(os):
    for i in range(os.shape[0]):
        print("Offspring number : {}\t".format(i), end="")
        rv = np.random.uniform(-1, 1, 1)
        val = np.random.randint(os.shape[1])
        print("{} -> ".format(os[i]), end='')
        os[i, val] = os[i, val] + rv
        print("{}".format(os[i]))
    
    return os

In [8]:
'''
    For running the GA algorithm, the following steps are:
    1. Generate population
    2. Calculate Fitness
    3. Select fittest individuals for crossover
    4. Crossover
    5. Mutate
    6. New population generated
'''
generations = 5
parents_mating = 3

print("-------------- INITIAL POPULATION --------------")
print(new_population)
print()

for g in range(generations):
    print("---------- GENERATION {} ----------".format(g+1))
    print("-------------- FITNESS --------------")
    fitness = Fitness(X, y, new_population)
    print()
    print("------- SELECTING MATING POOL -------")
    parents = SelectMatingPool(new_population, fitness, parents_mating)
    print()
    print("------------- CROSSOVER -------------")
    osc = Crossover(parents, offspring_size=(population_size[0] - parents.shape[0], num_weights))
    print()
    print("-------------- MUTATION -------------")
    osm = Mutation(osc)


    new_population[0:parents.shape[0], :] = parents
    new_population[parents.shape[0]:, :] = osm
    print()
    print("-------------- NEW POPULATION --------------")
    print(new_population)
    print()

-------------- INITIAL POPULATION --------------
[[ 4.21639113  4.85300525  3.59710741]
 [ 1.79574497 -0.11266811 -3.50650847]
 [-2.07217627 -0.55469658 -1.77361774]
 [-2.38262337 -2.85779011  3.57027661]]

---------- GENERATION 1 ----------
-------------- FITNESS --------------
Member of population : 0
(1)(4.216391125566526) + (0)(4.853005246391568) + (0)(3.5971074073262947) + (1)(4.216391125566526) + (0)(4.853005246391568) + (1)(3.5971074073262947) + (1)(4.216391125566526) + (1)(4.853005246391568) + (0)(3.5971074073262947) + (1)(4.216391125566526) + (1)(4.853005246391568) + (1)(3.5971074073262947) + Dataset average = ([325.52298199])/(4) = [81.3807455]

Member of population : 1
(1)(1.795744974605844) + (0)(-0.11266810514577674) + (0)(-3.5065084674662863) + (1)(1.795744974605844) + (0)(-0.11266810514577674) + (1)(-3.5065084674662863) + (1)(1.795744974605844) + (1)(-0.11266810514577674) + (0)(-3.5065084674662863) + (1)(1.795744974605844) + (1)(-0.11266810514577674) + (1)(-3.50650846746

In [ ]:
weights = new_population[np.argmin(fitness)]
print("Final Weights are : {}".format(weights))

Final Weights are : [-2.40127035  1.51411704 -3.0082145 ]


In [ ]:
print("Truth table for the given boolean function : ")
print("A\tB\tY\tH")
print("-----"*7)
for i in range(X.shape[0]):
    for j in range(1, X.shape[1]):
        print("{}\t".format(X[i, j]), end = '')
    print("{}\t".format(0 if y[i, 0] == -1 else 1), end='')
    print('{}'.format(0 if np.dot(X[i], weights) < 0.5 else 1))  

Truth table for the given boolean function : 
A	B	Y	H
-----------------------------------
0	0	0	0
0	1	1	0
1	0	1	0
1	1	0	0
